### ISSUE TITLE
Change order + Common Y-Axis

### ISSUE THREAD

**Issue by Da-ThomasS** [ioBroker/ioBroker.flot#100]
Hi, Flot is a really awesome tool to create charts. Thank you for this!

I have two feature requests, that would make it even better.

At first a functionality to reorder the lines is missing. It would be the best, if there were Down/Up Buttons in each line.

Second I sometimes use more than 5 lines, but the Common Y-Axis just accepts a value up to 5. I can change it in the link, and it works then, but it's really time-consuming to do it after every change. Maybe you could just increase the Combo-Box or make it as a Text-Field.

Thank you for reading.

Best regards
Thomas

**Comment by baennjer** [comment]
Have you tried eCharts? It's the new tool to create charts in ioBroker. Holds all the features you've described and is more sophisticated compared to FLOT.
https://github.com/ioBroker/ioBroker.echarts
