### ISSUE TITLE
Plot calculated / combined values

### ISSUE THREAD

**Issue by thomas725** [ioBroker/ioBroker.flot#101]
**Is your feature request related to a problem? Please describe.**
In some cases I'd like to plot the difference of two variables, or even more complex calculated values.

**Describe the solution you'd like**
It would be great if alternatively to specifying a single variable ID in the ID column we could specifiy formulas containing multiple IDs.

**Describe alternatives you've considered**
Can't think of any alternative to reach that goal...

**Additional context**
Let's try it with an example:
I've got the output of my photovoltaik-system in the variable `modbus.0.holdingRegisters.1.40091_W`.
And I've got the sum of the output of my photovoltaik-system with the consumption all devices drawing from PhaseA in `modbus.0.holdingRegisters.240.40099_WphA`.
Now it would be great if I could plot not just those two variables (that have recorded histories in my `sql.0` instance) but also a combination of them, like:
`[modbus.0.holdingRegisters.240.40099_WphA]+[modbus.0.holdingRegisters.1.40091_W]/3`

**Comment by Apollon77** [comment]
I think best practice is to use a javascript to calculate the relevant values and store them into an own state that you then can plot. because of the fact that most likely the values will not be written "at the same micosecond" it will be very hard to determine what to use for the calculation. Alternaively use Influxdb and you could use other queries in Grafana or such

**Comment by thomas725** [comment]
Thanks for the quick reply!

I do believe that it's not too hard to come up with an algorithm to overcome that hurdle of non matching timestamps.
If you meant the problem is it can't be easily done in SQL, let's load all the used variables separately (as if we would if we wanted to plot them separately). Then we could use all the timestamps of the first variable and either just get the closest values from the other variables or interpolate between the two closest ones.

I'm willing to try to implement this myself, though I would very much appreciate it if you could guide me a bit where I could find the relevant places in the source files..

**Comment by Apollon77** [comment]
Pleas ehcek out echarts adapterwhich is "flot of the future" and maybe open issue there please.
