### ISSUE TITLE
Werte < 01.01.2000 (in sqllite gespeichert) werden nicht angezeigt

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.flot#104]
Wie im Titel erwähnt, werden die Werte älter als 01.01.2000 nicht im Diagramm angezeigt.
vgl. auch thread:
https://forum.iobroker.net/topic/44738/sql-wert-per-script-speichern/28

**Comment by bahnuhr** [comment]
Das Problem besteht weiterhin.

**Comment by baennjer** [comment]
Da FLOT nicht mehr weiter entwickelt wird musst du mal eCharts ausprobieren. Das ist der Nachfolger und ist voll in iob integriert.

**Comment by Apollon77** [comment]
ne das Thema liegt in history und den anderen Adaptern aus einem Grund. Wier kamen denn die >2000 Daten rein? Von ioBroker damals geloggt oder irgendwie manuell importiert?

**Comment by bahnuhr** [comment]
@baennjer 
Wo steht das denn, dass flot nicht mehr weiterentwickelt wird?
Hab ich bisher nicht gelesen.
Genauso weinig, dass eChrats ein nachfolger sein soll.

**Comment by baennjer** [comment]
@bahnuhr 
https://forum.iobroker.net/topic/39172/test-echarts-adapter
![image](https://user-images.githubusercontent.com/32200998/130328484-d7461b9d-7787-4c77-897b-868ab1e0cec8.png)

**Comment by Apollon77** [comment]
@bahnuhr ja ist so, wobei wir Community PRs auch für flot gern noch annehmen. neue Features werden aber von Bluefox seite eher nicht mehr dazu kommen
