### ISSUE TITLE
Flot Editor ohne Funktion nach Upgrade auf Web-Adapter 4.1.0

### ISSUE THREAD

**Issue by xdaamg** [ioBroker/ioBroker.flot#113]
Beim Adapter Flot-Diagramme Version 1.10.7 funktioniert der Editor nach einem Upgrade des Web-Adapters (und des socketio-Adapters) auf 4.1.0 nicht mehr. Die Editor-Seite ist weitgehend leer und es können keine Diagramme geladen oder editiert werden. Nach einem Downgrade des Web-Adapters auf 3.4.16 funktioniert der Editor wieder.

Es gibt zwar inzwischen einen Hinweis bei Upgrade des Web-Adapters, jedoch dürfte für den Endnutzer nicht klar sein, welche Adapter davon tatsächlich betroffen sind (es ist lediglich von minuvis die Rede), der Flot-Editor scheint davon auch betroffen zu sein.

Flot-Diagramme: 1.10.7
Web-Adapter: 4.1.0
Node.js: v14.18.3
NPM: 6.14.15
admin: 5.2.3

**Comment by MK-66** [comment]
@Apollon77 
Der Editor des Flot Adapters 1.10.7 funktioniert auch bei mir nur, wenn man im neuen Web Adapter 4.1.1 den Haken bei „Reine Web-Sockets (iobroker.ws) verwenden“ nicht setzt. 

Ohne den Haken habe ich dann aber leider wieder die hohen 18MB Datenverbrauch wie von mir beim Web Adapter in dem bereits geschlossenen Issue „VPN Connection extremly slow…“ geschildert.

Also hoffe ich, dass Ihr als Entwickler den Flot Adapter so anpassen könnt, dass er auch mit der Funktion „Reine Web-Sockets (iobroker.ws) verwenden“ demnächst dann wieder funktioniert. Derweil behelfe ich mir einfach durch Haken ändern, bzw. durch eine zweite Web Instanz bei der der Haken nicht gesetzt ist.

Ansonsten wie schon so oft gesagt: Klasse Arbeit!

**Comment by Apollon77** [comment]
Gutes Feedback.  Als Workaround nutze ggf zwei web instanzen ... :-)

**Comment by xdaamg** [comment]
Ich schließe das mal wieder. Mit dem Web-Adapter 4.1.1 soll ja offenbar der Haken bei "reine Web-Sockets verwenden" nicht mehr standardmäßig gesetzt werden ("usePureWebSockets": false).
