### ISSUE TITLE
keine Voreinstellungen mehr gespeichert

### ISSUE THREAD

**Issue by Kampfratte** [ioBroker/ioBroker.flot#115]
Hallo,

wollte mal wieder was in FLOT ändern und habe es gestartet. Ich hatte da eigentlich einige Voreinstellungen gespeichert, doch die sind alle weg. Auch wenn ich aus der Grafik das Bearbeiten klicke, kommt nur eine leere Flot-Seite. Die URL der zu bearbetenden Seite wird zwar ganz kurz aufgerufen, aber refresht dann sofort auf flot/edit.html

**Comment by fu-zhou** [comment]
Ich kann das Verhalten leider bestätigen, kann aber nicht mehr nachvollziehen, ab welcher Host-/ Adapter-Version das Verhalten auftritt, es waren ziemlich viele Updates in letzter Zeit, die ich alle eingespielt habe (Repository: Beta Latest), alle Updates von heute sind drin (Host 4.0.15, Web 4.1.6, Flot 1.10.7, Downgrade von Flot hilft nicht). Das Ganze sieht so aus, dass "Voreinstellung" und "Eingangsdaten" leer ist, wenn man bei Eingangdaten auf "Linie hinzufügen" klickt, werden die schon Vorhandenen Linien angezeigt, aber weder ein Link wird sichtbar, noch kann man sich die Kurven im Editor anzeigen lassen. Im vis selber sind die Kurven weiterhin vorhanden.

**Comment by fu-zhou** [comment]
Hier die Lösung: im Web Adapter den Haken rausnehmen bei "Reine Web-Sockets (iobroker.ws) verwenden"

Siehe auch: [https://github.com/ioBroker/ioBroker.flot/issues/113#issuecomment-1028053136](url)

**Comment by Kampfratte** [comment]
Wenn ich den Haken raus mache, startet der web alle paar Sekunden neu und bleibt nicht an. Warum auch immer.

**Comment by Apollon77** [comment]
<was sagen die Logs?

**Comment by Kampfratte** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/37498878/154857047-4a8bd5eb-e28c-423e-a7b0-f3123e545eeb.png)

**Comment by GermanBluefox** [comment]
Please test 4.2.0

**Comment by Kampfratte** [comment]
@GermanBluefox getestet und es funktioniert nun auch wieder mit iobroker.ws wie gewohnt. 

Danke dir
