### ISSUE TITLE
Flot Editor 1.10.7 funktioniert nur teilweise mit Web Server Adapter 4.1.x

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.flot#116]
Der Flot Editor V1.10.7 funktioniert nicht sobald im Web Server Adapter V4.1.x der Haken „Reine Web-Sockets (iobroker.ws) verwenden“ gesetzt wird. 

Es können dann keine Datenpunkte angegeben bzw. auch keine history Instanz gewählt werden und zuvor erstellte und gespeicherte Flots sind allesamt nicht sichtbar. Speichern ist auch nicht möglich und der sonst bekannte Button "Speichern" wird im Editor als etwas kleinerer "Save" Button angezeigt und ist ohne Funktion. 

Das Setzen des besagten Hakens „Reine Web-Sockets (iobroker.ws) verwenden“ im Web Server Adapter ist für mich sehr wichtig, da hierdurch der Datenverbrauch beim mobilen VPN Zugriff auf meine VIS relativ klein und somit recht schnell ist.

Momentan behelfe ich mich einfach mit zwei Web Server Instanzen, einmal mit Haken für die VIS und einmal ohne Haken für den Flot Editor. Ich hoffe oder wünsche mir daher, dass der Flot Adapter diesbezüglich in einer kommenden Version nochmal angepasst werden kann.

Besten Dank

**Comment by Apollon77** [comment]
Please try the very latest web version from just this afternoon
