### ISSUE TITLE
Preview not working anymore (in current chrome)

### ISSUE THREAD

**Issue by mswiege** [ioBroker/ioBroker.flot#117]
The preview in the flot testing page (http://...:8082/flot/edit.html) is not working anymore in the current chrome version (I have Version 99.0.4844.86 on Chromebook). 

The preview at the bottom of the page just shows a grey background and isn't sized correctly to the full available height. 
![image](https://user-images.githubusercontent.com/1588581/160802991-d8797526-c300-4987-8e0a-b67574ffe82b.png)

Opening in a new window also shows just the grey area (and a bit of the legend)
![image](https://user-images.githubusercontent.com/1588581/160803369-df9c1a14-fd00-4518-987a-693d54b46509.png)

BUT:
- In an old firefox version (v 94.0.2) the previews work
- The "real" charts in the vis work, also in that chrome version where the preview is not working

In the console I can see this warning message:

> DevTools failed to load source map: Could not load content for http://192.168.1.50:8082/lib/js/socket.io.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

But that same message is also shown in the vis and there it works, so this is probably not the issue.

For some of my chart I also see this error message which sounds like this could be the issue but the strange thing is that it is not shown for all my charts but all my charts are not working anymore:
> jquery.flot.min.js:7 Uncaught Error: Invalid dimensions for plot, width = 0, height = 0
>     at U.resize (jquery.flot.min.js:7:1)
>     at new U (jquery.flot.min.js:7:1)
>     at jquery.flot.min.js:7:1
>     at new i (jquery.flot.min.js:7:1)
>     at Function.J.plot (jquery.flot.min.js:8:1)
>     at chart.js:637:1
>     at new CustomChart (chart.js:178:1)
>     at prepareChart (data.js:484:1)
>     at data.js:754:1
>     at readMarkings (data.js:656:1) 

My iobroker (and adapter) are all up-to-date:
- Plattform: linux
- Node.js: v14.19.1
- NPM: 6.14.16
- iobroker 4.0.21
- flot: 1.10.7
- socket.io: 4.2.0
- Web socket: 1.3.0

**Comment by spitfire4all** [comment]
Same problem here.

![image](https://user-images.githubusercontent.com/25489051/161379923-f1fd962b-02b3-4368-81e2-c13941ebd354.png)

**Comment by Apollon77** [comment]
is there any error in the  browser console?

**Comment by spitfire4all** [comment]
See no errors but i´m not a developer.

![image](https://user-images.githubusercontent.com/25489051/161384332-8b3ecd83-47fd-45a2-870f-3338d07ada1b.png)

**Comment by spitfire4all** [comment]
Is this a Browser Problem ?
Any hints about ?

**Comment by Apollon77** [comment]
Any hin in the Browse rerror console? Aber a blöocked iframe content or such?

**Comment by spitfire4all** [comment]
Jetzt mal auf Deutsch, scheint mir so als habe da die Recht schreib Korrektur beim Handy zugeschlagen :-)
Welche Error Konsole meinst du? Ich hatte ja oben etwas gepostet, das reicht nicht aus?
Sehe da nicht das irgendetwas blockiert wird, kann ich das irgendwo nach schauen?

Gruß
Hans-Dieter

**Comment by mswiege** [comment]
The error messages of the browser console have been posted by me in the first post. No additional messages (like blocked iframes or such).

**Comment by mswiege** [comment]
> See no errors but i´m not a developer.
> 
> ![image](https://user-images.githubusercontent.com/25489051/161384332-8b3ecd83-47fd-45a2-870f-3338d07ada1b.png)

Du müsstest oben rechts bei den Tabs noch auf "console" klicken, um die Fehlermeldungen zu sehen (bei dem Screenshot bist du gerade auf dem tab "Elements").

**Comment by spitfire4all** [comment]
Ok, das sieht schon anders aus:

![image](https://user-images.githubusercontent.com/25489051/165340874-05d1d73d-3169-4a4a-a04f-f3e27840be73.png)

**Comment by Apollon77** [comment]
Also bei mir im Chrome tut es ... daher jetzt mal noch bitte web version und ggf socketio version posten und Konfig

**Comment by Apollon77** [comment]
@spitfire4all Das 404 von dem .map File kannst Du ignorieren ... Interessanter ist eher der Fehler obendrüber ... aber ich hab auch keine Idee wo der herkommen könnte

**Comment by spitfire4all** [comment]
web.0 - v4.3.0
socketio.0 - v4.2.0

Chrome - Version 101.0.4951.67


Plattform
linux
Betriebssystem
linux
Architektur
x64
CPUs
1
Geschwindigkeit
1640 MHz
Modell
Intel(R) Core(TM) i5-3470T CPU @ 2.90GHz
RAM
4 GB
System-Betriebszeit
280 T. 16:05:31
Node.js
v14.19.0 (Es gibt eine neuere Version: v14.19.3)
time
1653727216278
timeOffset
-120
Anzahl der Adapter
415
NPM
6.14.16

**Comment by spitfire4all** [comment]
Here is the solution.

https://forum.iobroker.net/topic/58841/float-vorschau-bzw-float-funktioniert-nicht-im-browser/13

Regards 
Dieter

**Comment by mswiege** [comment]
Can confirm that the height/width settings in the options are the issue. They have been set to "2" and after deleting those, preview works as expected.
Don't know where the "2" came from but I think it is fine to close this bug now.
