### ISSUE TITLE
Werte < 1.1.2000

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.flot#119]
Hallo @Apollon77

der "Fehler" besteht immer noch:

Daten mit Daten < 1.1.2000 (ts < 994481200000) werden nicht in zB Flot angezeigt
siehe https://forum.iobroker.net/topic/44738/sql-wert-per-script-speichern/48

Gibt es da schon eine Lösung ?

mfg
Dieter

**Comment by Apollon77** [comment]
Please try Github version ... version number stay the same ... restart web after update. Github installs can currently take upto 10+mins when executed with npm 6!

**Comment by bahnuhr** [comment]
Bei dem Versuch über git zu installieren kommt der Hinweis:
Dieser Adapter kann nicht von  git installiert werden, da er vorher gebaut werden muss.

**Comment by Apollon77** [comment]
flot 1.11.0 geht raus
