### ISSUE TITLE
Flot: Keine Charts mehr angezeigt?

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/ioBroker.flot#125]
**Describe the bug**  
Hi, hat sich irgendetwas geändert bei FLOT?
Ich habe alte Diagramme, die auf einmal nichts mehr anzeigen, auch im Edit kommt nur ein schmaler schwarzer Balken und nicht das gewohnte Bild.
Daten sind definitiv vorhanden, die kann ich im Datenpunkt sehen.

<img width="1835" alt="image" src="https://user-images.githubusercontent.com/53481090/208513748-48e26a8e-c742-4f5b-8b8e-d313a47f6159.png">

Welche Informationen kann ich dazu noch liefern, damit jemand einen Tipp hat, was ich ggfls noch anpassen muss?

LG

**To Reproduce**  

**Expected behavior**  
Display of charts as usual in the past

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: <adapter-version>. 1.11.0

**Additional context**

**Comment by Apollon77** [comment]
Der web adapter - nutzt der socket io oder ws/"pure websockets"??

**Comment by MichaelSchaaf999** [comment]
In den Einstellungen vom Adapter web.0 habe ich definitiv nichts geändert, hier die Screenshots der Parameter:

***@***.***

***@***.***
***@***.***

Liebe Grüße
Michael


Michael Schaaf  | Telefon +49 (0)7172 – 91 67 56 1   |   Mobil  +49 172 –  52 33 6 33  | Fax +49  (0)7172 – 93 400 30   | Mail ***@***.******@***.***>


Von: Ingo Fischer ***@***.***>
Antworten an: "ioBroker/ioBroker.flot" ***@***.***>
Datum: Montag, 19. Dezember 2022 um 21:53
An: "ioBroker/ioBroker.flot" ***@***.***>
Cc: Michael Schaaf ***@***.***>, Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.flot] Flot: Keine Charts mehr angezeigt? (Issue #125)


Der web adapter - nutzt der socket io oder ws/"pure websockets"??

**Comment by Apollon77** [comment]
Please add attachements direktly to github .... not working as email attachements

**Comment by Apollon77** [comment]
Ich denke es liegt an "Reine websockets verwenden"

**Comment by MichaelSchaaf999** [comment]
Ok, dann schlägst Du vor, den Haken da rauszunehmen?
Dann mache ich das jetzt, danke.
Da wurde doch vermutlich etwas anderes (websockets?) geändert, so daß dieser Reine-Websockets-verwenden-Haken dann auf einmal negative Auswirkungen hatte, denke ich. 
Gab's so ein ähnliches Issue nicht schonmal im Juli'22?
Egal: Ich nehme den Haken dann jetzt raus.

Danke, Ingo!

LM
M

**Comment by Apollon77** [comment]
Problem ist das ohne den Haken pot der Vis editor nicht mehr tut. Sind aber da dran

**Comment by MichaelSchaaf999** [comment]
Ah, gut zu hören.

Aber: Haken bei Reine-Websockets ist raus, trotzdem tut's der Flot-Editor noch nicht wieder:

![image](https://user-images.githubusercontent.com/53481090/208605792-a3fbbdeb-1e93-446f-80d6-547a7b39cb2a.png)

LG 
M

**Comment by MichaelSchaaf999** [comment]
Bestätigt: VIS Editor tut's auch nicht mehr.

**Comment by MichaelSchaaf999** [comment]
> Sind aber da dran

Dear Ingo,
any idea regarding the time frame? Don't want to push, though.
Best
M

**Comment by Apollon77** [comment]
Come when it comes, sorry, nothing more concrete. But it's on the list

**Comment by MichaelSchaaf999** [comment]
Okay, I ticked ´Reine Websockets verwenden´ again, to be able to edit
Graphs are nice to have, but not essential. 
Well, in a hospital graphs would be important not to show a flat line on the screen for e.g. a hartbeat. But iOB is not used in hospitals, I assume.
So thank you for taking care and have a good day!

**Comment by Apollon77** [comment]
In fact you still can work with two web instances and use flot with both ... so editor on one and charts on the other

**Comment by MichaelSchaaf999** [comment]
interesting: I did not know that.
So just adding another web.0 instance? No, sorry: The second web instance then will be web.1

![image](https://user-images.githubusercontent.com/53481090/208927160-88d3abee-a7b7-4757-b979-a23516f13a81.png)

Has the web.1 to be configured in a special way?
And are editor and charts selecting there path to the web instance on their own?

**Comment by Apollon77** [comment]
Did you provided an unique port nunber fpor the second instance? The same/defauklt port in two instances will not work

**Comment by MichaelSchaaf999** [comment]
Yes, different port for web.1:
![image](https://user-images.githubusercontent.com/53481090/209118053-d4e7225b-4da7-4f6c-a212-5c1afe1690b8.png)

Do I have to tell this additional port to any other iOB instance or adapter? Is it normal to have two web-instances, any advantage for speed or similar?

**Comment by Apollon77** [comment]
It depends what you use and such ... that highly depends on what you have on otherindtances ... use the new one just for cases where pure websockets do not work ... you will see what you maybe need tochange

**Comment by MichaelSchaaf999** [comment]
Thx.
This is the 8083 web.1:
![image](https://user-images.githubusercontent.com/53481090/209127168-b733c83a-8877-4570-9b62-2561501e7f69.png)

But even with this the flot adapter does not work:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/53481090/209127674-087e46a7-c021-4938-ba88-193e180dbbd1.png">

May be it's the better idea to wait for you fixing this issue than pushing for alternate solutions.

**Comment by derrapf** [comment]
Ich bin auch daran interessiert, dass das gefixt wird. Ich habe die web.0 Einstellungen eben wegen VIS geändert und nun geht Flot nicht mehr. Ich brauche das aber dringend.
Wäre super wenn ihr das zeitnah hinbekommen würdet, oder einen Workaround findet. Da wäre ich sehr dankbar.
Gruss Ralf

**Comment by Apollon77** [comment]
Bitte neueste flot und ws versionen testen

**Comment by derrapf** [comment]
Hallo Apollon77
Alle meine Adapter sind uptodate.
So ging es bei mir:

Ich habe eine zweite Instanz von web gemacht: web.1 und so eingstellt:
![grafik](https://user-images.githubusercontent.com/11745094/209824890-fcb7128c-9348-4e45-9585-5d6d4ae9505a.png)

Wenn man nun Flot über diesen Port aufruft geht's wieder
http://<IP>:20002/flot/edit.html


mein web.0 ist so eingestellt. Damit geht's nicht:
![grafik](https://user-images.githubusercontent.com/11745094/209824991-cae3978c-17d5-48ae-83af-56a5e14b82c9.png)

Gruss Ralf

**Comment by MichaelSchaaf999** [comment]
Ich habe web.0 und web.1 auch so eingestellt: Aber trotzdem habe ich nur diesen schmalen Streifen der Ausgabe...
<img width="675" alt="image" src="https://user-images.githubusercontent.com/53481090/209841553-e0f8b200-f24c-40ba-a37f-cf109130ac0e.png">

Funktioniert so leider nicht. Flot hab ich schon einmal entfernt und neu installiert, aber das brachte keine Abhilfe.

**Comment by RV3Dtech** [comment]
Kann das bestätigen auch mit 1.12.0 wird nur der Schwarze Balken angezeigt.

**Comment by derrapf** [comment]
Dann ist das was Anderes, würde ich behaupten.
Ich habe vorhin aus dem latest 1.12.0 und damit geht es.
Gruss Ralf

**Comment by RV3Dtech** [comment]
hmm, ok, 
Bei mir sieht es so aus: 

![Screenshot 2022-12-27 222755](https://user-images.githubusercontent.com/50876608/209869765-78a82c2e-0053-4ed5-950a-4ae5ebeaa902.png)

Ich hab nichts in Flot verändert oder sonst was angepasst. Bisher hat das einwandfrei Funktioniert. Das update auf 1.12.0 hat bei mir nichts verbessert.

Grüße
Jan

**Comment by derrapf** [comment]
Ich bin inzwischen auf eCharts umgestiegen. Ist besser. Somit brauche ich auch Flot nicht mehr. Probierts  mal aus. Einfach mal goggeln.

**Comment by MichaelSchaaf999** [comment]
eCharts ist mir zu aufwendig.
Und Flot funktioniert leider immer noch nicht, sorry.

**Comment by derrapf** [comment]
>eCharts ist mir zu aufwendig.
Was ist Dir da zu aufwendig? Das ist eigentlich identisch mit Flot ausser dass das Userinterface anders ist. Und die Grafik in VIS ist dazu auch noch relational. D.h. wenn Du die Parameter in eCharts änderst siehst du es sofort in der VIS.
Ist für mich eher einfacher als Flot.
Ausserdem wird in Zukunft eCharts FLOT ersetzen wenn ich Apollon richtig verstanden habe, insofern inverstiere ich da nix mehr.
Gruss Ralf

**Comment by sensenmann** [comment]
Bei mir funktioniert nun alles. Das Problem war ganz ein anderes (MySQL war nach SD-Karten-Crash defekt). Ich hoffe, ihr könnt das Problem bei euch noch lösen!

**Comment by MichaelSchaaf999** [comment]
### Was ist Dir da zu aufwendig?
Lieber Ralf,
das Problem, das zum Statement "zu aufwendig" führte, lag einzig und allein bei mir.
Ich sah im Tutorial innerhalb weniger Sekunden ein Script, JS/Blockly, und kam aus nicht nachvollziehbaren Gründen zu der falschen Erkenntnis, man müsse ein Script schreiben, um in eCharts einen Graphen zu erzeugen.
Mea culpa. Sorry.
Deinem Hinweis bzw. Deiner Frage "was ist... zu aufwendig" bin ich dann nachgegangen und konnte meinen Irrtum erkennen. Denn eCharts hat eine sehr brauchbare GUI, ähnlich wie Flot, und Sripte sind da für was ganz anderes (Graphen per Telegram verschicken).
Nun: Gesagt getan - die ersten Testgraphen hab ich in eCharts erstellt und halte das für einen mindestens vollwertigen Ersatz für Flot.
Deshalb folge ich Deinem Rat und setze alle Grafikausgaben von Flot auf eCharts um
Vielen Danke für die Hilfe und Aufklärung! Das war sehr sehr hilfreich.

LG
Michael

**Comment by MichaelSchaaf999** [comment]
Für mich hat sich dann Flot erledigt, danke sehr. Deshalb schließe ich diesen Thread.

**Comment by derrapf** [comment]
Hallo Michael
Freut mich dass ich Dir helfen konnte. ECharts ist auch nicht perfekt, aber ich finde tatsächlich gut, dass man es dirkt in VIS einbinden kann und Änderungen in der Darstellung direkt durchschlagen ohne dass man am VIS was ändern muss.
Das ging bei Flot irgendwann auch mal; aber wie gesagt: Nachdem man mir sagte dass wohl Flot nicht mehr weiter entwickelt wird und es bei eCharts weitergeht, war es klar dass ich umsteigen musste.

Gruss Ralf
