### ISSUE TITLE
ignore NULL

### ISSUE THREAD

**Issue by smiling-Jack** [ioBroker/ioBroker.flot#13]
in der index.html steht:

```
          if (res[i].val === null) {
                    if (option.ignoreNull || i == res.length - 1) {
                        res[i].val = lastVal;
                    } else {
                        lastVal = null;
                    }
                }
```

dadurch wird null auf den letzten Wert gesetzt. 
Mein Problem ist aber ich habe ich habe zb. stark hallende Werte die dann bei einem Wert von z.B. 0 stehen bleiben und sich für längere Zeit nicht ändern. (In meinem Fall z.B. eine Pumpendrehzahl) History zeichnet die 0 auch auf. Allerdings wird durch die Aggregation (averrage) keine 0 an Flot übergeben somit habe ich dann unschöne horizontale Linien im Diagramm die sehr verwirrend sind.

Ich würde mir wünschen das man die Punkt "ignore null" ändert in:
"get null as": last val || 0 || ignore

@BF was hältst du davon ? Soll ich das machen ?

**Comment by Pmant** [comment]
Das klingt wie der Bug den ich in der aggregate.js im SQL Adapter gefixt habe. Ich denke das muss im im History Adapter auch gefixt werden?!

ioBroker/ioBroker.sql@1fc67566ea934a6b0118ce07411fe6ee3c2b11dc

**Comment by smiling-Jack** [comment]
Vom Prinziep ist es besser es direkt bei der aggregation zu machen das stimmt dann müssen aber alle adapter gleich gemachte werden die daten loggen. 

Dann aber nicht wie im SQL da man dann immer eine 0 anstat null bekommt was auch nicht richtig ist.

Man sollte schon diese drei Auswahlmöglichkeiten haben  last val || 0 || ignore

**Comment by Pmant** [comment]
wieso bekommt man immer eine 0?

**Comment by smiling-Jack** [comment]
Sorry hatte mich im committ verkuckt hast recht der giebt auch null aus.

**Comment by bf** [comment]
@Pmant @smiling-Jack Jungs ihr habt mich oben mit @bf referenziert, deswegen bekomme ich permanent E-Mails von euch. Bitte achtet doch darauf, dass ihr nicht so viele Rechtschreibfehler macht. 

Ich krieg bei jeder Notificaiton aus diesem Thread die Mega-Krise. 

Wenn ihr euch später mal irgendwo bewerbt, dann werden auch solche Threads angeschaut weil das hier alles public ist. Viel Erfolg noch mit eurem Projekt.

**Comment by GermanBluefox** [comment]
Immer noch aktuell?
