### ISSUE TITLE
Flot not opening anymore

### ISSUE THREAD

**Issue by MSal-RPI4** [ioBroker/ioBroker.flot#141]
**Describe the bug**  
Flot not opening.

**To Reproduce**  
Simply trying to open Flot and edit preset.
**Expected behavior**  
Able to edit preset.

**Screenshots & Logfiles**  
<img width="918" alt="20231223_Iobroker_Flot" src="https://github.com/ioBroker/ioBroker.flot/assets/97038647/62c0d2f7-0bf4-4b83-ba01-e17e75eaa959">

**Versions:**  
 - Adapter version: 1.12.0
 - JS-Controller version: <js-controller-version>  5.0.17
 - Node version: <node-version>  18.19.0
 - Operating system: <os-name> RPI 4B, 4GB 64Bit Raspbian

**Additional context**  
Have been using Flot successfully for year.
Even installed system entirely from scratch, but after restoring backup unfortunately same behavior again :-(.
Also, could this be possibly an issue of too many history datapoints ?  Received a message about 30.000 datapoints and I'm planning to restructure to redis but was hoping I can get this resolved first ?!

**Comment by Apollon77** [comment]
Any errors in your browser javascript error console?

**Comment by MSal-RPI4** [comment]
Resolved after delete of one present and history adapter re-installation.
