### ISSUE TITLE
stuck at loading screen when using auth

### ISSUE THREAD

**Issue by Pmant** [ioBroker/ioBroker.flot#18]
https://github.com/ioBroker/ioBroker.flot/blob/4463b4bbdc128cd60bcfcd530299eaaed7dabf8c/www/js/data.js#L162

When using VIS with AUTH flot Charts just stay on the loading screen for ever. Debugging led me to this line which seems to break the dataflow since something is not ready to read data. Replacing it with
```
setTimeout(readData,100);
```
seems to fix it but feels wrong.

**Comment by GermanBluefox** [comment]
Fixed as suggested
