### ISSUE TITLE
File index.html not found

### ISSUE THREAD

**Issue by cernst1980** [ioBroker/ioBroker.flot#21]
Wenn man im Admin auf die Instanz des Adapters klickt, kommt folgende Fehlermeldung:

File index.html not found

**Comment by Homoran** [comment]
Bei Flot gibt es nichts zu konfigurieren, daher sollte (ist jetzt) der Schraubenschlüssel nicht anwählbar sein. Es existiert kein Konfig-File.

Issue kann geschlossen werden

**Comment by cernst1980** [comment]
Passt, danke.
