### ISSUE TITLE
Perma Link wäre schön

### ISSUE THREAD

**Issue by wuast94** [ioBroker/ioBroker.flot#22]
Mir ist aufgefallen das wenn man mit flot chart ein chart macht durch die Einstellungen einen link generiert und diesen wo auch immer einbinden kann .. was aber ärgerlich ist wenn man charts an mehreren orten verwendet und etwas ändern will muss man den neu generierten link erst überall wieder einfügen. 

wäre schön wann man da ne art Verlinkung machen könnte
vorstellbare wäre da eine art config file
name | perma link | generierter link 
(nur ein bsp geht sicherlich schöner) 

so könnte man in Visualisierungen den perma link benutzen und wenn man was ändert an nem chart braucht man nur die eine Datei ändern. schöner wäre natürlich wenn es direkt einen link gibt der anstatt die config einen namen hat .. machts auch übersichtlicher :)

**Comment by GermanBluefox** [comment]
Es ist schon teilweise implementiert. In die Visualisierung sollte es noch
kommen.

2018-01-21 12:59 GMT+01:00 wuast94 <notifications@github.com>:

**Comment by sbormann** [comment]
Gibt es hier etwas Neues?
Man kann ja die Presets bereits abspeichern - das ist ja schon mal klasse. 
Jetzt kann es doch eigentlich nur noch ein kleiner Schritt sein, diese auch aufzurufen, oder?
LG
