### ISSUE TITLE
x-axis: month with dot and weekdays

### ISSUE THREAD

**Issue by drtp** [ioBroker/ioBroker.flot#23]
Hi,

although there is an option for the x-axis to display the month with an additional dot ("hh-mm DD.MM.") it will not be displayed properly. Would love to see this fixed.

In addition, I would like to have an option showing the weekdays ("Mo, Tu,... Su", preferably also in German language "Mo, Di,... So") on the x-axis.

Regards,

Thorsten

**Comment by drtp** [comment]
Nothing happened here so far.

**Comment by GermanBluefox** [comment]
Here nothing, but on the other adapters.

пн, 7 мая 2018 г., 10:28 drtp <notifications@github.com>:

**Comment by GermanBluefox** [comment]
I mean: there are limited number of developers. And they was/are busy with
other adapters. Not charts

вт, 8 мая 2018 г., 12:20 drtp <notifications@github.com>:

**Comment by drtp** [comment]
Ah, okay. 

Well, perhaps you can fix this issue some day. I will be patient. ;)
