### ISSUE TITLE
Kein Scrollbalken für Presets in V1.7.0

### ISSUE THREAD

**Issue by JustMe1791** [ioBroker/ioBroker.flot#24]
In der Version V1.7.0 gibt es leider keine Möglichkeit durch die Liste der Presets zu scrollen. Es ist kein Scrollbalken vorhanden. Getestet unter Windows 10 mit Google Chrome und Mozilla Firefox (aktuellste Version). Nur im IE ist die Scrollleiste vorhanden.

**Comment by JustMe1791** [comment]
Korrektur: Laut ioBroker ist V1.7.7 ist installiert, die Anzeige in Flot zeigt jedoch V1.7.0 an.

**Comment by bigd-73** [comment]
Das Problem kann ich bestätigen. Gibt es dazu schon eine Lösung?

**Comment by GermanBluefox** [comment]
Kann nicht reproduzieren:
Chrome
![image](https://user-images.githubusercontent.com/4582016/39605092-45c34aee-4f2f-11e8-9da7-931f28a0da8c.png)
Firefox
![image](https://user-images.githubusercontent.com/4582016/39605113-59262b10-4f2f-11e8-92f8-a8d0bd947794.png)

**Comment by bigd-73** [comment]
... merkwürdig. Laut Admin ist bei mir die Version 1.7.9 installiert. In Flot steht oben rechts aber die Versionsnummer 1.7.0. Vielleicht hängt es damit zusammen. Neuinstallation kann ich ja keine machen weil sonst die Presets verloren sind, oder?

**Comment by JustMe1791** [comment]
Firefox 59.0.3

Flot-Version 1.7.7, kein Scrollbalken:
![flot_scrollbar_missing_177](https://user-images.githubusercontent.com/38461875/39659233-43c47c40-5024-11e8-8c70-05e1912616a3.png)

Habe die Flot-Version auf 1.7.9 aktualisiert, trotzdem kein Scrollbalken:
![flot_scrollbar_missing_179](https://user-images.githubusercontent.com/38461875/39659234-4c259072-5024-11e8-9566-e4715ea06405.png)

Auch auf meinem Samsung Galaxy 7 Edge fehlt der Scrollbalken mit Firefox.

Unter Edge und Chrome sind Scrollbalken mit 1.7.9 vorhanden, ich benutze aber nur Firefox...

Evtl. liegt es daran, das bei meinen Einträgen durch die IDs mehrzeilig sind?

**Comment by drtp** [comment]
In der Tat fehlt bei Firefox der seitliche Scrollbalken. Man kann aber das untere Halbfenster mit der Maus herunterziehen. Dann sieht man die restlichen Einträge. Ist allerdings nicht ganz so komfortabel.

**Comment by GermanBluefox** [comment]
Fixed in 1.9.0
