### ISSUE TITLE
Preset geht beim Ändern des Namens verloren

### ISSUE THREAD

**Issue by bigd-73** [ioBroker/ioBroker.flot#25]
Hallo,

sobald ich den Namen eines Presets ändere taucht es nicht mehr in der Liste auf.
Passiert aber nicht jedes mal. Manche lassen sich ändern und erscheinen in der Liste,
andere wiederum verschwinden.

SG
Mario

**Comment by mhandschuher** [comment]
Daß Presets verschwinden ist mir auch schon mehrmals passiert. Allerdings konnte ich nicht reproduzieren, unter welchen Umständen das geschieht.
