### ISSUE TITLE
Markierungen funktionieren nicht mehr

### ISSUE THREAD

**Issue by Elr0n** [ioBroker/ioBroker.flot#27]
Hi,

nach einem Update von 1.7.9 -> 1.9.0 funktionieren all diejenigen Charts nicht mehr, die Markierungen (selbst definierte Linien) benutzen. Entfernt man diese, klappt wieder alles einwandfrei. 
Auch in komplett neuen Charts führt das Hinzufügen einer beliebigen Markierung dazu, dass die Charts nicht mehr funktionieren -> Der Chart (auch die Vorschau) wird nicht mehr angezeigt und das Ladesymbol kreist in die Ewigkeit ;)

Gruß

Sebastian

**Comment by Apollon77** [comment]
Gibt die Browser Konsole irgendwelche Fehler aus?

**Comment by GermanBluefox** [comment]
Konnte reproduzieren. Heute Abend kommt ein fix.

**Comment by Elr0n** [comment]
Danke, ich habe eben die Version 1.9.1 getestet, und die Markierungen sind wieder da. Allerdings gibt es jetzt ein neues (kleineres) Problem: Die Markierungen liegen nicht mehr (wie bisher) im Vordergrund (überlagern also sichtbar die Messwerte / Linien / Balken), sondern im Hintergrund (und werden entsprechend verdeckt).
