### ISSUE TITLE
Diagramme werden mit Version 1.9.0 nicht mehr angezeigt.

### ISSUE THREAD

**Issue by Hypnos3** [ioBroker/ioBroker.flot#28]
Mit Version 1.9.0 kommt anstelle des Diagramms nur die Ladeanimation:
![photo5233551958554552586](https://user-images.githubusercontent.com/12692680/40892057-9b6a5fee-6791-11e8-8ffd-bde743d438eb.jpg)

node -v = v6.12.2
nodejs -v = v6.14.1

Web habe ich Version 2.3.4

Bin zurück auf Version 1.7.9 und es geht wieder. (Mit Version 1.8.0 kam ein Problem beim installieren.)

**Comment by Apollon77** [comment]
Gibt die Browser Konsole irgendwelche Fehler aus?

**Comment by GermanBluefox** [comment]
Sind die Markierungen dabei?

**Comment by Hypnos3** [comment]
Ja, sind Markierungen dabei.

**Comment by Apollon77** [comment]
Dann duplicate von #27 ?!

**Comment by Hypnos3** [comment]
1.9.1 behebt das Problem
