### ISSUE TITLE
Feature Request: Flot - Adapter Presets direkt per http/https aufrufen

### ISSUE THREAD

**Issue by Hardwarefreak** [ioBroker/ioBroker.flot#31]
Schön wäre es die Presets z.B. in der Form:

h t t p://127.0.0.1:8082/flot/preset.html?Spritpreise aufzurufen, anstatt dem exterm langen Seitenaufruf, der die gesamte Konfiguration enthält, z.B.:
h t t p://127.0.0.1:8082/flot/index.html?l%5B0%5D%5Bid%5D=hm-rega.0.18106&l%5B0%5D%5Binstance%5D=sql.0&.... titleSize=16&legend=sw&legColumns=3 ... u.s.w. "

damit wäre dann höchstwahrscheinlich auch issue #22 erledigt  ;-)

**Comment by darkbrain85** [comment]
Gibt es in dieser Sache irgendwelche Fortschritte?
Es ist wirklich SUUUPER nervig wenn ich in meinem VIS Projekt bei Design Änderungen jeden Flot Link anpassen muss. 
Ein Aufrufen des Presets per Link wäre wirklich eine erhebliche Erleichterung.

**Comment by Apollon77** [comment]
PRs welcome

**Comment by sbormann** [comment]
Hallo,

folgende Datei kann das.

Einfach als preset.html im www-Ordner von Flot abspeichern (ggf. mit chown die Rechte anpassen!).

Aufruf: 
- \<ip\>:8020/flot/preset.html - listet alle Presets auf
- \<ip\>:8020/flot/preset.html?preset=\<presetName\> - ruft direkt <presetName> auf

@Apollon77 : **Kannst Du das bitte als PR ins Repo einfügen?**
Bin mit dem ganzen Github-Kram leider nicht so fit.

Hoffe, es hilft!
LG!!

````
<html>
	<head>
		<title>Flot Preset</title>
		<link href="img/favicon.png" rel="shortcut icon" type="image/x-icon"></link>
		<link type="text/css" rel="stylesheet" href="../../lib/css/themes/jquery-ui/default/jquery-ui.min.css"></link>
		<script type="text/javascript" src="../../lib/js/jquery-1.11.1.min.js"></script>
		<script type="text/javascript" src="../../lib/js/socket.io.js"></script>
		<script type="text/javascript" src="../../_socket/info.js"></script>
		<script type="text/javascript">
			var presets         	= {};
			var currentChart    	= null;
			var loaded          	= false;
			var instance        	= 0;
			var socket;

			function init() {
				console.log('Initialize...');
				var params = location.href.split('?')[1];
				if (params && params.match(/^preset=/)) {
					currentChart = params.replace(/^preset=/, '');
				}
				setTimeout(function () {
					initSocket();
				}, 200);
			}
			
			function initSocket() {
				console.log('Init connection...');
				// Read instances
				socket = io.connect(socketUrl, {
					query: {
						key: socketSession
					},
					reconnectionDelay: 10000,
					reconnectionAttempts: Infinity,
					upgrade: typeof socketForceWebSockets !== 'undefined' ? !socketForceWebSockets : undefined,
					rememberUpgrade: typeof socketForceWebSockets !== 'undefined' ? socketForceWebSockets : undefined,
					transports: typeof socketForceWebSockets !== 'undefined' ? (socketForceWebSockets ? ['websocket'] : undefined) : undefined
				});

				socket.on('connect', function () {
					console.log('Connected');
					setTimeout(function () {
						socket.emit('name', 'flotPreset');
					}, 50);
					setTimeout(function () {
						getPresets(socket, function () {
							console.log("Got presets");
							console.log(presets);
							if (currentChart && presets[currentChart]) {
								loadChart(currentChart);
							} else if (currentChart && presets["flot." + instance + "." + currentChart]) {
								loadChart("flot." + instance + "." + currentChart);
							} else {
								showPresets();
							}
						});
					}, 100);
				});

				socket.on('disconnect', function () {
					console.log('Lost connection');
				});

				socket.on('error', function (e) {
					console.error('Socket error: ' + e);
				});
				socket.on('connect_error', function (e) {
					console.error('Socket error: ' + e);
				});
			}

			function getPresets(socket, callback) {
				// read presets
				socket.emit('getObjectView', 'chart', 'chart', {
					startkey: 'flot.' + instance + '.',
					endkey: 'flot.' + instance + '.\u9999'
				}, function (err, res) {
					presets = {};
					loaded  = true;
					if (res && res.rows) {
						for (var i = 0; i < res.rows.length; i++) {
							presets[res.rows[i].value._id] = res.rows[i].value;
						}
					}
					callback && callback();
				});
			}
						
			function showPresets() {
				var presetList = "";
				for (var id in presets) {
					if (!presets.hasOwnProperty(id)) continue;
					var obj = presets[id];
					presetList += "<a href='index.html?" + obj.native.url + "' data-role='button'>" + obj.common.name + "</a><br>";
				}
				$('#presetList').html(presetList);
			}
			
			function loadChart(id, callback) {
				window.location.replace("index.html?" + presets[id].native.url);
				callback && callback();
			}
			
			$(document).ready(init());
			
		</script>
	</head>
	<body>
		<p id="presetList">loading...</p>
	</body>
</html>
````

**Comment by Apollon77** [comment]
Ok kurze Frage: diese ganzen "Kurz Timeouts " ... was tun die? Stellen die sicher das bestimmte Anfragen nur nach kurzen Wartezeiten rausgeht. Warum die Wartezeiten? Sind die nötig?

**Comment by Apollon77** [comment]
ahh ich sehe das die auch im sonstigen code so drin sind

**Comment by Apollon77** [comment]
Bitte 1.10.0 vom GitHub testen und Feedback geben

**Comment by sbormann** [comment]
> Ok kurze Frage: diese ganzen "Kurz Timeouts " ... was tun die? Stellen die sicher das bestimmte Anfragen nur nach kurzen Wartezeiten rausgeht. Warum die Wartezeiten? Sind die nötig?

Gute Frage, ich weiß es auch nicht. Habe den Code so übernommen ohne es auszuprobieren.

**Comment by Apollon77** [comment]
:-) Ok bitte mal testen die neue Version

**Comment by mifricke** [comment]
Hi!

Danke für diese schöne Änderung.

Leider funktioniert das bei mir nicht. Mein Flot Verzeichnis hat aber auch keinen www Folder. Bei erneutem Upload wird auch 

> INFO: Directory "/opt/iobroker/node_modules/iobroker.flot/www" was not found! Nothing was uploaded or deleted

gemeldet. Ist meine Installation kaputt? Sonst funktioniert Flot wie gewünscht. Keine weiteren Probleme.

**Comment by Apollon77** [comment]
aahhh ... hm ... ok ich release mal auf npm ... installiere dann richtig, ich glaube flot github install geht so nicht

**Comment by Apollon77** [comment]
versuch mal mit npm install iobroker.flot (im iobroker dir!!) und iobroker upload flot danach

**Comment by mifricke** [comment]
Ändert leider nichts. Weiterhin kein www Ordner. Upload meckert wieder wie oben...

**Comment by mifricke** [comment]
Ich würde Flot ja mal entfernen, aber wo speichert der die Presets? Die würde ich gerne behalten! ;-)

**Comment by Apollon77** [comment]
nix da entfernen ... muss so gehen :-)

Also ganz langsam:
* cd /opt/iobroker
* npm install iobroker.flot
* prüfen das er die 1.10.0 installiert
* gern prüfen das in node_modules/iobroker.flot ein www Verzeichnis ist
* jetzt iobroker upload flot

Bitte mal gesamtes Log/Ausgaben posten

**Comment by mifricke** [comment]
Hier die Terminal Ausgabe:

`root@debian:/opt/iobroker# npm install iobroker.flot
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/ch                                               okidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                               2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                               )
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.5 (no                                               de_modules/osx-temperature-sensor):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-tempe                                               rature-sensor@1.0.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux"                                               ,"arch":"x64"})

+ iobroker.flot@1.10.0
updated 1 package in 21.741s

23 packages are looking for funding
  run `npm fund` for details

root@debian:/opt/iobroker#
`

**Comment by Apollon77** [comment]
Ok,

und jetzt fehlt das oben genante "iobroker upload flot"

**Comment by mifricke** [comment]
Ach so... ja... das hatte ich natürlich gemacht und dabei keine Veränderung zu der oben gepusteten Fehlermeldung festgestellt:

`root@debian:/opt/iobroker# iobroker upload flot
upload [0] flot.admin /opt/iobroker/node_modules/iobroker.flot/admin/flot.png flot.png image/png
INFO: Directory "/opt/iobroker/node_modules/iobroker.flot/www" was not found! Nothing was uploaded or deleted.`

**Comment by Steff42** [comment]
Funktioniert bei mir!
Endlich muss ich die ewig langen Links nicht mehr eingeben!
Eine Frage bzw. einen Wunsch hätte ich dennoch: Der Preset-Name darf aktuell keine Umlaute (äöü) enthalten. Lässt sich das noch integrieren? Sonst muss ich eben bei den Namen die Umlaute entfernen.
Gruß Steffen

**Comment by sbormann** [comment]
Ja, ich versuchs und schreibe einen PR
VG

**Comment by Steff42** [comment]
@sbormann,
habe die Änderung aus deinem PR mal bei mir getestet, schaut gut aus!!
Gruß Steffen

**Comment by mifricke** [comment]
Ich habe nach Wochen mal wieder versucht mein bereits oben beschriebenes Problem zu lösen. 
Kein www Ordner in Sicht. Erstelle ich ihn mit den entsprechenden Rechten, ist er nach einem Upload wieder weg. 

Leider komme ich nicht weiter. Ich erhalte weiterhin folgende Ausgaben:

`root@debian:/opt/iobroker#  npm install iobroker.flot
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (cu                                                                       rrent: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@^1.0.5 (node_modules/iobroker.info/node_modules/osx-tem                                                                       perature-sensor):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","ar                                                                       ch":"any"} (current: {"os":"linux","arch":"x64"})

+ iobroker.flot@1.10.0
updated 1 package in 18.201s

25 packages are looking for funding
  run `npm fund` for details

root@debian:/opt/iobroker# iobroker upload flot
upload [0] flot.admin /opt/iobroker/node_modules/iobroker.flot/admin/flot.png flot.png image/png
Update "system.adapter.flot.0"
INFO: Directory "/opt/iobroker/node_modules/iobroker.flot/www" was not found! Nothing was uploaded or deleted.`

**Comment by thomas725** [comment]
Hallo! Tolles Projekt, vielen dank für die geniale Chart-Möglichkeit!

Das aufrufen der Presets funktioniert bei mir jedoch leider nicht, bekomme nur den fehler:
`File preset.html not found: Not exists`

Hab mal die Tipps getestet die @mifricke fürs selbe problem bekommen hat:
```
/opt/iobroker# npm install iobroker.flot
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ iobroker.flot@1.10.0
updated 1 package in 45.421s

/opt/iobroker# ls -a node_modules/iobroker.flot/
.  ..  admin  docs  gulpfile.js  img  io-package.json  lib  LICENSE  .npmignore  package.json  package-lock.json  README.md  src  test  .travis.yml

/opt/iobroker# find . -iname preset.html
./node_modules/iobroker.flot/src/preset.html

/opt/iobroker# iobroker upload flot
upload [0] flot.admin /opt/iobroker/node_modules/iobroker.flot/admin/flot.png flot.png image/png
Update "system.adapter.flot.0"
INFO: Directory "/opt/iobroker/node_modules/iobroker.flot/www" was not found! Nothing was uploaded or deleted.
```

Hmm. Und nun? Hilfe! :(

**Comment by mifricke** [comment]
Top @thomas725!

Dieser Workaround klappt auch bei mir! Danke für das teilen hier! 
Vielleicht kann @Apollon77 ja was dazu sagen... Warum ist das so?

**Comment by Apollon77** [comment]
Wie habt ihr flot denn installiert? Bitte nehmt einfach aus dem latest repo und nicht vom GitHub. Das sollte an sich alles released sein oder https://github.com/ioBroker/ioBroker.flot/blob/master/README.md#1100-2020-05-14

**Comment by Apollon77** [comment]
Install von GitHub geht bei flog nicht.

**Comment by thomas725** [comment]
okey. war ein workaround versuch, weil eben mit der default install methode beim verwenden des preset.html nur dieser fehler kommt:
`File preset.html not found: Not exists`

**Comment by Apollon77** [comment]
Mag sein das im STABLE Repo noch eine ältere Version ist. Latest Repo hat die 1.10

**Comment by thomas725** [comment]
Ich bekomm den Flot Adapter nicht mehr hin in meinem IO-Broker. Auch komplett entfernen und neu installieren bringt nix. Bekomme immer dieser Javascript error `Uncaught ReferenceError: settings is not defined` und damit funktioniert die edit.html nicht mehr...

**Comment by Apollon77** [comment]
Hast Du mal Cookie und vor allem Browser local Storage gelöscht?
