### ISSUE TITLE
X-Achse Offset bei zwei Datenpunkten falsche Skalierung

### ISSUE THREAD

**Issue by WaJoWi** [ioBroker/ioBroker.flot#32]
Siehe: https://forum.iobroker.net/viewtopic.php?f=20&t=15133#p159158

**Comment by DutchmanNL** [comment]
Feature request : Option hinzufügen wie bereits vorhanden für die Y-Achse (usw Common)

Das Problem ist wen man 2 Datenpunkte wählt und zeitverzögert wiedergibt ( z.b 2ter Wert X-Achse Offset = 1Tag), die X-Achse zum 2 ten Datenpunkt eine kleine Zeitverschiebung hat zum ersten Datenpunkt
