### ISSUE TITLE
Bug in der Werteanzeige (Bar-Graph)

### ISSUE THREAD

**Issue by mhandschuher** [ioBroker/ioBroker.flot#34]
In der aktuellen Version (1.9.1) des Adapters können bei der Bargraph-Anzeige auf Wunsch die zugehörigen Werte angezeigt werden. Das funktioniert allerdings nur bei der ersten ausgewählten Instanz. Fügt man eine weitere Instanz mit Bargraph-Anzeige hinzu, fehlen dort die Werte. Sobald man eine Markierungslinie hinzufügt, verschwinden die angezeigten Werte komplett (siehe auch https://forum.iobroker.net/viewtopic.php?f=22&t=15736)

**Comment by mhandschuher** [comment]
![bar-label_1](https://user-images.githubusercontent.com/40818158/43359073-9d3dd14e-929c-11e8-98a2-285729b860e7.JPG)

**Comment by mhandschuher** [comment]
![bar-label_2](https://user-images.githubusercontent.com/40818158/43359074-a8b09520-929c-11e8-9260-62ed06efe592.JPG)

**Comment by bassbumper** [comment]
Hallo,

gibt es hier einen Stand?
Ich habe das gleiche Problem in Version 1.9.1. Sobald man eine Markierung hinzufügt verschwinden alle Werte in dem Bar-Chart. Entfernt man die Markierung sind alle Werte wieder sichtbar.

**Comment by mhandschuher** [comment]
Tja, ist halt ein Freiwilligen-Projekt und wenn der "zuständige" Entwickler keine Zeit hat dann bleiben die Bugs halt. Schade nur, daß das auch innerhalb des ioBroker-Teams niemand zu interessieren scheint. Meine Meldungen sind immerhin schon ein halbes Jahr alt :(

**Comment by Apollon77** [comment]
Den unterstellenden und vermuteten Teil hier lasse ich mal unkommentiert.

Flot ist recht speziell und komplex. Sich da einzuarbeiten erfordert einiges an Zeit und Aufwand und ist nicht mal ebenso gemacht. Und auch nicht jeder hat die ahnung von Browser JavaScript entwicklung. 

Ich behaupte daher eher das im ioBroker Team die Entwickler sinnvoll priorisieren wofür die ihre zeit verwenden, auch wenn dies den Nebeneffekt hat das die wenigen die sich ggf mit Flot auskennen Zeit finden müssen neben ihren ändern Baustellen um sich dieses bugs anzunehmen. Stattdessen gibt es große Fortschritte sn anderen stellen.

**Comment by Apollon77** [comment]
PS: wir nehmen gern PullRequests an die den bug fixen.

**Comment by bassbumper** [comment]
Ich habe mal versucht die Stelle zu identifizieren wo die Werte für die Bars generiert werden. Innerhalb von 10 min aber kein Erfolg :) Scheint auch nicht trivial zu sein ;) Wenn ich mehr Zeit habe oder mir jemand einen Tip gibt kann ich versuchen es zu fixen.

**Comment by Apollon77** [comment]
coooool ... Danke!!

Option 1 Änderungen beschreiben sodass man es nachbauen kann.

Option 2 (preferred) mach einen Pull Request. 
Der geht im einfachen Fall auch sehr einfach. Geh hier im Github auf das file, klicke oben rechts auf den Stift, mache die nötigen Änderungen, runterscrollen, eintragen was du geändert hast mit ner Überschrift und details. Auswahl so lassen, dann macht er nen Pull request. 
Wenn Du mit git vertraut bist kannst DU auch Repo forken, änderung lokal machen und dann daraus den PR machen :-)

**Comment by bassbumper** [comment]
Ich gehe mal für Option 2. Es gibt für alles ein erstes Mal :)

**Comment by Apollon77** [comment]
Checke ich spätestens heute Abend!

**Comment by mhandschuher** [comment]
Schön daß sich da jemand engagiert. Allerdings ist das nur *ein* Bug von etlichen, die hier gemeldet wurden. Ich denke da vor allem an die selten funktionierende Umbenennung von Presets und besonders an den Datenverlust (Preset), falls eine Umbenennung mal ausnahmsweise klappt.
