### ISSUE TITLE
Wrong display of data (bar graph)

### ISSUE THREAD

**Issue by mhandschuher** [ioBroker/ioBroker.flot#37]
There's a bug within the visualisation of bar graphs (see screenshot 1: purple graph): the daily sum (stored every day at 23:45) is display for the current day and with wrong value (even for the previous days). Once one waites for dhe auto-update, the graph is showed correctly (1,2 at 29/7/2018 23:45 / previous day 0,80; screenshot 2). It's also correct when zooming out (screenshot 3) and wrong again when returning to the 100% display. Displaying only the purple graph works correctly

**Comment by mhandschuher** [comment]
![strom gas_2w-1](https://user-images.githubusercontent.com/40818158/43382919-a55c4b06-93d9-11e8-8e7e-1034e4277374.JPG)

**Comment by mhandschuher** [comment]
![strom gas_2w-2](https://user-images.githubusercontent.com/40818158/43382929-b364465e-93d9-11e8-9d3d-93fcd79c56cd.JPG)

**Comment by mhandschuher** [comment]
![strom gas_2w_zoom](https://user-images.githubusercontent.com/40818158/43382939-bc17d662-93d9-11e8-8744-73050c26a98b.JPG)

**Comment by foxriver76** [comment]
Sometimes I experience something similar with a line graph. E. g. The max value in the week was 9000 watts then it updates a minute later and the max value it shows is around 6000. So he sometimes visualizes outlier values which does not seem to exist.
