### ISSUE TITLE
Color Picker funktioniert nicht

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.flot#47]
Mir ist aufgefallen, das bei FLOT in der Version 1.9.2 der "Color Picker" Kreis nicht funktioniert - egal mit welchem Browser (immer in der aktuellsten Version).
Es wird in jedem Auswahl Fenster in dem man Farben definieren könnte, immer nur oben links ein rotes Kästchen angezeigt.

Ich weiß nicht ob das evtl. bekannt ist?

**Comment by knudi76** [comment]
Ja, ist bei mir genau so. Gibt es schon eine Lösung?

**Comment by jraichle** [comment]
bei mir genau so. Geht es bei jemandem?

**Comment by jlegen** [comment]
den Colorpicker (jquery.colorpicker.css)  scheint offenbar kaum jemand zu benutzen, jedenfalls ist der bis zum heutigen Tag wohl falsch verlinkt. Daher starte ich nach jedem Update ein kleines "Fixscript", um in der Datei
node_modules/iobroker.flot/www/edit.html
den Pfad "lib/css/jquery.colorpicker.css" durch
"css/jquery.colorpicker.css" zu ersetzen:
`sed -i -e "s|lib/css/jquery.colorpicker|css/jquery.colorpicker|g" node_modules/iobroker.flot/www/edit.html`
`iobroker upload flot`
Danach tut er's dann; vielleicht kann das jemand mit Schreibrechten hier mal einpflegen...

**Comment by Apollon77** [comment]
fixed in 1.10.2

**Comment by JBSullivan** [comment]
Der Color Picker funktioniert jetzt perfekt. Bitte die 1.10.2 ins stable überführen. Ich arbeite auch oft Remote mit  ioB und in der ioB-Cloud wird mir immer noch die Version 1.9.2 von FLOT angezeigt. Vielen Dank.

**Comment by Apollon77** [comment]
Das hilft nicht. Das muss flot auf den Cloud Servern aktualisiert werden. Das wäre ein Cloud Ticket.
