### ISSUE TITLE
Multihost

### ISSUE THREAD

**Issue by homecineplexx** [ioBroker/ioBroker.flot#52]
Wenn der FLOT auf einem Slave eingerichtet wird, und man klickt bei der Instanz auf das Symbol "Adapter Webseite öffnen" wird die URL vom Master aufgerufen (zB: http://192.168.1.22:8082/flot/edit.html) dabei läuft es auf zB http://192.168.1.23:8082/flot/edit.html Slave.

Allerdings wird dann die Seite aufgebaut und dann bekommt man eine Meldung "No Connection to Server" und man kann auch nichts machen.

**Comment by Apollon77** [comment]
Bitte das issue im Admin Repo anlegen. Danke
