### ISSUE TITLE
No SQL-Datapoints selectable

### ISSUE THREAD

**Issue by IO-Link** [ioBroker/ioBroker.flot#53]
I cannot select SQL-Datapoints in the flot-instance, for some time now. Only one datapoint from the history-adapter is selectable - i added that datapoint only for testing.
The flot-adapter is working apart from that, the .vis shows the flot-diagrams from SQL-datapoints i made some time ago correct.

The screenshot shows the history-datapoint - no SQL-datapoint is selectable.
![2019-01-17 20_47_01-window](https://user-images.githubusercontent.com/45272881/51432080-17844e00-1c32-11e9-8337-a631bb145419.png)

**Comment by Apollon77** [comment]
Please use Admin v3. Admin v2 is EOL

**Comment by IO-Link** [comment]
> Please use Admin v3. Admin v2 is EOL

Installed version is 3.5.10:
![2019-01-20 19_17_25-window](https://user-images.githubusercontent.com/45272881/51443362-1f9ec500-1ce8-11e9-8aa7-a2aef4452b12.png)

**Comment by Apollon77** [comment]
Ok, dann bitte im Admin Adapter ein Issue öffnen
