### ISSUE TITLE
A widget for Flot - get URL from flot objects (like an iFrame)

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.flot#56]
Wish: A widget that works like the iFrame widget, but gets the Flot object from ioBroker as input value (and gets the URL from here) = flexible, dynamic handling of the flots

See: https://forum.iobroker.net/topic/19971/flot-url-in-vis-über-flot-0-objekt-anstatt-iframe

**Comment by Lueghi** [comment]
Is there a chance of realising for this issue?
