### ISSUE TITLE
crash with more than 14 input lines

### ISSUE THREAD

**Issue by xmace** [ioBroker/ioBroker.flot#57]
with 14 inputs everything nice:
![image](https://user-images.githubusercontent.com/15639172/53080028-0ca22f00-34f8-11e9-9f62-084739918be2.png)

but when i add another input:
![image](https://user-images.githubusercontent.com/15639172/53080100-3196a200-34f8-11e9-9f98-730da483b9ad.png)

independend which input is choosen.

**Comment by sepp68** [comment]
How long is the URL ?
https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by SpikeNbg** [comment]
Hi!
I have the same problem (since yesterday)..

In my case, 13 Inputs run smooth, but with the 14the Input line it breaks..

The only differnce in my case (URL hasn't changed):
I've **upgraded from node 6.12.2 to 8.15.1** yesterday. 

After the upgrade 2 flot grafics aren't working any more.. Like said earlier, the URL didn't Change, as it is embedded in 3 vis pages..

**Comment by Bongo2** [comment]
I have the same problem. After updating Node from 6 to 8. If there are too many lines or too many options.
Is there an explanation or solution?

**Comment by nooxnet** [comment]
I'm pretty sure that has something to do with the url length. In my case I have 12 with an url length of 6578. When I add another line I get a 400 Bad Request HTTP-Error. I assume the maximum allowed url length is usually a setting of the web server or the web framework. Could this be a setting of node or the web adapter of ioBroker?

If course we are far over the recommended max url length. But this is also true for just a few lines in Flot. Modern web browsers should be able to handle more and so it's probably just a setting on the server side.

**Comment by nooxnet** [comment]
Ok, they changed the max header size in nodejs v12.6.0+ from 80 to 8 kB:
https://stackoverflow.com/questions/32763165/node-js-http-get-url-length-limitation
https://github.com/nodejs/node/issues/24692
