### ISSUE TITLE
Smoothing resets after refresh

### ISSUE THREAD

**Issue by xolom** [ioBroker/ioBroker.flot#66]
I have problems with the smoothing attribute. It works for the first time, but when it reloads the smoothing is gone. Anyone has the same issue?

**Comment by Dax88** [comment]
Same problem here!

**Comment by oberstel** [comment]
same problem here with flot 1.9.2 as well as with 1.10.2

**Comment by Dax88** [comment]
Problem still exists with flot 1.10.6
