### ISSUE TITLE
File edit.html not found: Not exists

### ISSUE THREAD

**Issue by Andi19851985** [ioBroker/ioBroker.flot#70]
Hallo,
ich habe den Flot Adapter schon mehrmals auf verschiedene Art und Weise versucht zu installieren aber leider ohne erfolg.
Die Installation läuft problemlos und der Adapter ist auch aktiv.
Leider kommt folgende Meldung (File edit.html not found: Not exists) wenn ich den Adapter aufrufe.
Ich weis nicht was ich noch machen soll.
Node, Nodejs und npm ist auf dem aktuellen Stand.
![node](https://user-images.githubusercontent.com/42984555/63066111-e8546780-bf08-11e9-8feb-9aaf714b63d0.jpg)
![web](https://user-images.githubusercontent.com/42984555/63066114-ebe7ee80-bf08-11e9-9c60-56cb537b02cf.jpg)
![system](https://user-images.githubusercontent.com/42984555/63066124-f1ddcf80-bf08-11e9-902f-b32cbf388ced.jpg)

**Comment by Apollon77** [comment]
Try „iobroker upload flot“ on command line or use the upload  button in admin on „adapters“

**Comment by Andi19851985** [comment]
hallo,
danke für die schnelle Antwort.
eine Neuinstallation des Flot Adapters über die command line hat funktioniert.

Vielen Dank

**Comment by Apollon77** [comment]
Neuinstallation? Oder das upload?

**Comment by Andi19851985** [comment]
Upload hat aus irgendeinem Grund nicht funktioniert.
Habe den Flot Adapter komplett gelöscht  und über die command line neu installiert.
