### ISSUE TITLE
Zeitscala Zeitzone

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.flot#71]
Leider wird die Mitte von zwei Tage mit 14:00 angegeben.
Es ist auch schon eine Lösung vorhanden, die leider im ioBroker nicht
eingestellt werden kann. Sehr ärgerlich.
Siehe hier:
https://forum.iobroker.net/topic/12973/zeitskala-inm-flot-adapter/2

**Comment by Apollon77** [comment]
Wo ist die "Lösung"? FInde nix ausser andeutungen

**Comment by Hans-Zwiesel** [comment]
Der Beitrag von  harvey637 am 25. Juni 2018, 12:27 im
https://forum.iobroker.net/topic/12973/zeitskala-inm-flot-adapter/2
war gemeint.
Ich habe mir aber nicht getraut es auszuprobieren.

**Comment by Apollon77** [comment]
siehe 1.10.3
