### ISSUE TITLE
Datenquelle sql.0 fehlt / Diagramme können nicht gespeichert werden

### ISSUE THREAD

**Issue by christianh17** [ioBroker/ioBroker.flot#80]
In meinem Flot Adapter kann ich seit kurzem die sql-Instanz nicht mehr auswählen. Es gibt nur noch die Möglichkeiten das Feld leer zu lassen oder aus dem Drop-Down-Menü "default" auszuwählen. Da ich meine Daten aber in einer Mysql-Datenbank logge möchte ich diese auch darstellen.

Das im Cache vorhandene Diagram funktioniert jedoch ohne Probleme.

Gleichzeitig kann ich meine Diagramme nicht mehr abspeichern. Genauer: Ich speichere sie ab wie immer, sie werden auch in der Übersicht (Voreinstellung) angezeigt aber wenn ich auf den Laden-Knopf drücke kommt nur eine "not found" Fehlermeldung.

Ich habe Flot und den Webserver deinstalliert und neu installiert, alle Adapter sind auf aktuellen Versionen.

Hat jemand von Euch eine Idee was ich tun könnte?
Danke!

**Comment by TeslaNator** [comment]
Ich habe das Problem seit kurzem auch bei zwei meiner Installationen (Ubuntu und Windows).

**Comment by Apollon77** [comment]
... Und du denkst das das antworten auf ein seit fast 2 Jahren geschlossenes Issue dann hilft? ;-)

**Comment by Apollon77** [comment]
Wenn Du willst das sich jemand darum kümmert ... ja .. dann bitte mit screenshot und auch mit info ob in der browser fehlerkonsole fehler stehen bzw was da steht

**Comment by TeslaNator** [comment]
Ich dachte, man könnte dieses wieder öffnen...

Das mit der Browserkonsole war schon ne gute Idee. Hat wohl was mit dem Websocket zu tun, den ich vor Kurzem installiert habe. Flot läuft zwar eigentlich auf Port 8082, macht aber Requests nach 8084, was dem neuen Websocket entspricht, den ich beim Web Adapter hinterlegt habe. Mir ist nicht ganz klar, warum Vis und Flot überhaupt noch auf 8082 erreichbar sind. 

Ich schau mal, ob ich das nicht selbst gelöst bekomme, wo ich jetzt mehr Infos habe. Danke schon mal hierfür.

Andernfalls erstelle ich ein Neues.
