### ISSUE TITLE
Feature Request: Multiplikator / Modifikator zusätzlich / statt Offset

### ISSUE THREAD

**Issue by thomas725** [ioBroker/ioBroker.flot#87]
Es wäre echt praktisch wenn man einer Variable nicht nur einen Offset aufaddieren könnte, sondern einen generischen Modifikator eintragen könnte der auch Multiplikationen erlaubt.

Oder eben Alternativ eine zusätzliches Config-Option, also Multiplikator und Offset getrennt voneinander.

**Comment by Apollon77** [comment]
Ist das wirklich etwas für den charting Adapter? Sollten nicht besser die Daten passend geliefert werden?

**Comment by thomas725** [comment]
hmm, naja die daten kommen hald von nem Plugin so daher. Ich fänds hald praktisch sie "on-the-fly" beim darstellen uminterpretieren zu können. ist imho. ähnlich wie das bereits existierende feature des offsets.

**Comment by thomas725** [comment]
also klassisch hat man in der softwareentwicklung daten in einer datenbank, in einem speziellen format.

Sind unterschiedliche Darstellungen gefordert, werden (wenn nicht aus performance gründen notwendig) die transformierten Daten nicht asynchron dupliziert gespeichert, sondern diese Transformation on the fly für die Darstellung vorgenommen.

**Comment by Apollon77** [comment]
@thomas725  Please have a look at echarts adapter ... flot will not be actively developed anymore, this one will

**Comment by thomas725** [comment]
after performance problems with echarts I retried flot and discovered that someone did implement this feature already in the meantime! :)

**Comment by Apollon77** [comment]
@thomas725 did you reported these "perfoemance problems" on echarts? If not please do so
