### ISSUE TITLE
Füllung geht nur bis zur Null-Line

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.flot#88]
Die Füllung von Linien endet immer bei der Null-Linie wenn man das Diagramm Fenster auf Minus Werte definiert hat (siehe rote Linie = -15 - Füllung endet bei 0). 

![2020-08-09 06_43_21-Flot Edit](https://user-images.githubusercontent.com/44617472/89725122-5c3a2a80-da0c-11ea-988b-f2a4b85432f6.png)

Beim Screenshot nicht wundern. Die Zahlen Werte sind "markiert", da man diese sonst nicht sehen könnte - ist halt doof, wenn man ein dunkles VIS Schema hat, und die Diagramm Werte deshalb in weiß eingestellt sind, bekommt man sie im FLOT Editor nicht angezeigt. Den FLOT Editor müsste man auch auf ein dunkles Schema umstellen können - aber das ist ein anderes Thema.

**Comment by thomas725** [comment]
Ich finde das "Enden der Füllung bei der 0-Linie" ist doch ein gewolltes Verhalten - Üblicherweise will man damit ja die "Fläche unter der Kurve" im Sinne von zwischen 0-Linie und Kurve darstellen, oder?

Zur Veranschaulichung ein hypothetischer Use-Case: X-Achse = Fliesgeschwindigkeit, Y-Achse = Zeit -> Fläche über der 0-Linie = vorwärts geflossene Menge, unter der 0-Linie = rückwärtsgeflossene Menge.

Welche Use-Cases gäbe es für das Füllen der Fläche unter einer Kurve bis zum unreren Ende des Diagrams statt zur 0-Linie?
