### ISSUE TITLE
Flot Adapter funktioniert nicht mehr

### ISSUE THREAD

**Issue by zgadgeter** [ioBroker/ioBroker.flot#90]
Hallo, ich hatte lange Zeit den Flot Adapter am laufen. Aber seid ca 3 Wochen funktioniert er nicht mehr. Wenn ich auf einer Flot Grafik gehe, kommt die Flot Seite, aber der Kreisel dreht sich nur. Habe den Flot Adapter schon deinstalliert, runter gesetzt auf jetzt 1.9.2 und den Socket IO auch mehrfach neu installiert, jetzt auf 3.0.13. Also alles auf stable. Nichts hilft...hat jemand noch einen Tipp?
Übrigens, das selbe ist so auf zwei unterschiedliche IOB Systemen die in einer VM laufen.

**Comment by Apollon77** [comment]
Was zeigt die Browser konsole an?

**Comment by zgadgeter** [comment]
Hallo, hieraus werde ich aber nicht schlau.
![image](https://user-images.githubusercontent.com/36098876/92412691-255f4d80-f14d-11ea-8e55-4da189687d3e.png)

**Comment by canim60** [comment]
Hallo Ingo, hab Flot zum ersten mal Installiert, leider kann ich keine IDs hinzufügen, die Liste ist a - Leer und das Fenster unten Dreht sich Permanent. Debug kann ich Starten, spuckt aber nichts raus. Hab versucht die IDS Manuell einzutragen, ohne Erfolg.

![Unbenannt1](https://user-images.githubusercontent.com/66805899/92534883-39cb4500-f236-11ea-8c23-428b154cd8d4.jpg)
![Unbenannt3](https://user-images.githubusercontent.com/66805899/92534890-3c2d9f00-f236-11ea-88c9-6e706cae4265.jpg)

**Comment by Apollon77** [comment]
Mal die latest bzw GitHub version versucht? Bzw welche Version habt ihr genutzt? 

@canim60 irgendwelche anderen Fehler in der Browser Konsole

**Comment by zgadgeter** [comment]
Hallo, also flot habe ich version 1.9.2 und socket.io 3.0.13. Aber ich habe mit Versionen schon update/downgrade gemacht. Flot dreht sich immer nur weiter...ich wuerde schon gerne die Daten auf einem Plot in meinem Vis zeigen. Vielleicht alles (flot/socket) loeschen?

**Comment by Apollon77** [comment]
@zgadgeter irgendwelche anderen Fehler in der Browser Konsole?

**Comment by canim60** [comment]
@Apollon77 ne leider keine anderen fehler..

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/93025663-0acf1d80-f600-11ea-979b-3455ac27b1f6.png)
Lokal geht auch.... Ich kann leider das Problem nicht reproduzieren...

**Comment by irudi** [comment]
Bei mir geht der auch nicht mehr. Braucht man denn den socket.io Adapter? Oder reicht die integrierte Instanz im webserver?

**Comment by irudi** [comment]
Das Problem wurde wohl beseitigt - bei mir funktioniert der Adapter mittlerweile wieder. Danke.
