### ISSUE TITLE
horizontale Linie wird nicht weitergeführt

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.flot#91]
In den weiteren Einstellungen kann man ja festlegen:
"null-Werte ignorieren: Linie wird horizontal weitergeführt"

Das funktioniert leider nur, wenn der erste Datenpunkt innerhalb des angezeigten Zeitfensters liegt.
Liegt der erste Datenpunkt vor dem angezeigten Zeitfensters, dann wird die horizontale Linie nicht angezeigt.

**Comment by Hans-Zwiesel** [comment]
Das Problem ist leider immer noch vorhanden.

**Comment by vain90** [comment]
Das selbe trifft mich leider auch. Ich habe einen Wert der sich nur relativ selten ändert.
Den kann ich aktuell so nicht vernünftig Monitoren. Der Wert wird auch nur dann geschrieben wenn sich wirklich etwas ändert da hilft es bei mir auch nicht das ich das "Nur Änderungen aufzeichnen" deaktiviere. Ich bekomme nur dann einen neuen Wert wenn sich der in der Quelle wirklich ändert.

Evtl. müsste ich mit einem JavaScript arbeiten welches mir den DP neu schreibt wenn er älter ist als 3h. Aber irgendwie ist das ja nicht Sinn der Sache oder?

Ich wäre auf jeden Fall sehr Dankbar wenn sich diesem Problem angenommen wird.
