### ISSUE TITLE
Uncaught Error: Invalid dimensions for plot, width = 0, height = 0

### ISSUE THREAD

**Issue by sonabit** [ioBroker/ioBroker.flot#92]
Since beginning of 2020 I have notice this errors. Now any updated chrome based browser doesn't show a chart

```
flot.js:formatted:1613 Uncaught Error: Invalid dimensions for plot, width = 0, height = 0
    at U.resize (flot.js:formatted:1613)
    at new U (flot.js:formatted:138)
    at flot.js:formatted:1387
    at new i (flot.js:formatted:1396)
    at Function.B.plot (flot.js:formatted:1747)
    at flot.js:formatted:3563
    at new CustomChart (flot.js:formatted:3599)
    at prepareChart (flot.js:formatted:3874)
    at flot.js:formatted:4014
    at readMarkings (flot.js:formatted:3966)
```

IOBroker - Flot Charts - 1.9.2 
![image](https://user-images.githubusercontent.com/114921/94618794-05cec700-02ac-11eb-85b6-af7ee85af2cc.png)

**Comment by simonssoftware** [comment]
I've got an similar problem with version 1.10.4.

![grafik](https://user-images.githubusercontent.com/50638485/102811812-45e2a900-43c6-11eb-90e9-609758b27287.png)

The only difference is that the charts sometimes load and sometimes not.

I'm using firefox on the pc and safari on the ipad. With both devices I have the same issue.
