### ISSUE TITLE
Zu viele Datenpunkte?? Hilfe

### ISSUE THREAD

**Issue by bug84** [ioBroker/ioBroker.flot#93]
Ich habe ein Problem mit flot, habe alle meine Charts mit Flot und es läuft super.
Aufgrund meines Problems bin ich seit Tagen am einrichten von Grafana, finde aber flot besser und möchte mein Problem schildern und hoffe sehr auf eine Lösung:

Ich nutze Flot mit InfluxDB (zuvor History, gleiches Problem.
Wenn ich einen Chart baue mit vielen Datenpunkten >15-17, dann erscheint einfach kein Chart mehr, als ob es eine Grenze von Datenpunkten gäbe. Irgendwann ab ca 10-15 Datenpunkten wählt flot nicht mehr selbstständig eine Farbe für den Datenpunkt, alle neuen sind dann blau.
Ab dem Punkt bekommt man noch 3-4 eingespeist in die Grafik und dann ist Schluss, die Grafik wird nicht mehr aktualisiert und ein leeres Feld wird als Vorschau gezeigt.

Mache ich was falsch oder ist das ein Bug?

Bitte Hilfe, brauche viele Datenpunkte, um alle meine RSSI Werte abzubilden, oder Temperaturen.!

![image](https://user-images.githubusercontent.com/57953379/99639408-d89acb80-2a47-11eb-9911-7bdae6698a61.jpeg)

**Comment by Apollon77** [comment]
steht irgendwas in der Browser Konsole wenn es passiert?
