### ISSUE TITLE
feature request: use "options -> header" ("Optionen -> Beschriftung") as http title

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.flot#94]
Hi (thanks for the browsertime :-)
when saving a chart all charts are named "flot charts" which ´make it difficult an neccessary to rename all charts immedeately. Same goes to using the link "show on new window", all charts are named equally "flot chart".

feature request: use the field "Optionen -> Beschreibung" if existing (might be something like "options -> description/header") as http header. This make saving charts a lot easyier, as most of the time ther will be no renaming. with non existing "description" an alternative idea might be using the name of the first datapoint/ maybe reduced to the device name ....

Easy identification of saved charts!

By the way: a "save URL" button to save the preset as link might also be handy. Clicking the preset (which is GREAT) starts the target link, not the preset link. So I have to type the preset instead of using a supplied link (in the form http://...../preset.html&preset=xxxxxxxx.html)

thanks 
Harvey

**Comment by harvey637** [comment]
Hi, sorry to see this feature request closed .... so sad :-.)
I still think this important for identification of tabs, sometimes I have 10++ flot/echarts tabs open and cannot remember which tab is which chart.
cu
Harvey

**Comment by baennjer** [comment]
FLOT  is discontinued. Use eCharts instead.

**Comment by harvey637** [comment]
yes, you will find the same request there too :-))))
But echarts is still a bit rough, like the date/time on the axis, I love the date only at midnight, hh:mm between. Also the hover field is (for me) nearly useless, as I cannot easy select what to display, and the background make a lot of colours unreadable. Maybe I should add some feature requests in echarts
thanks and cu
Harvey

**Comment by baennjer** [comment]
I know eCharts is not perfect yet but I think it will improve in the future
