### ISSUE TITLE
try to automagically identify float for displaying iobroker/objects/history tab (might be wrong forum - pls help)

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.flot#95]
Hi,
if a datapoint is marked for history (e.g. in influxdb adapter tabs and shown in a graphical tab/presentation of the data which is using the flot (adapter?).

All data is plotted as integer, which make not much sense if the data is float. Example: a temperature is displayed as line going up and down between temperatures from 19.1 to 19.9°C shows the correct line, but all points are displayed as 19°C, with no decimal. Same goes to the x-axis.

In the real float adapter I can adjust decimal points, but not here.
I have no idea where to search for the code, inside iobroker.admon, influxdb or float???

Any hint is appreciated, and I can try to describe the problem in the correct forum - thank you! 

(it might be an advanced feature for the flot adapter itself to auto identify the float/decmials instead of simply 2 decimals as default. But this is much better as using  integer as default as described in the request.

cu
Harvey

**Comment by Apollon77** [comment]
I think admin - because the "config" for the there included flot is coming from there - would be better choice. Please also check if such an issue is already there
